### ISSUE TITLE
rubrik_on_demand_snapshot sql parameters not supported

### ISSUE THREAD

**Issue by southcoastansible** [rubrik-devops/ansible-rubrik#115]
**Expected Behavior**

Please describe the behavior you are expecting.
On demand snapshot of sql database using rubrik_on_demand_snapshot task as specified by documentation.

**Current Behavior**

When using the sql_host and sql_instance parameters, the job fails specifying those are unsupported parameters.

**Failure Information (for bugs)**

Please help provide information about the failure if this is a bug.

"msg": "Unsupported parameters for (rubrik_on_demand_snapshot) module: sql_host, sql_instance Supported parameters include: api_token, fileset, host_os, node_ip, object_name, object_type, password, provider, sla_name, username"

* Use verbose outputs to capture any debug information.
```
`    - name: Rubrik On Demand Snapshot
      rubrik_on_demand_snapshot:
        node_ip: "{{rubrik_cluster_ip}}"
        username: "{{ rubrik_username }}"
        password: "{{ rubrik_password }}"
        object_name: "{{object_name}}"
        object_type: "{{object_type}}"
        sla_name: "{{SLA_name}}"
        sql_host: "{{SQL_host}}"
        sql_instance: "{{SQL_instance}}"
      register: rubrik_job_status`
```

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Install the rubrik_cdm module using pip install rubrik_cdm command

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.

```
Paste into a code block.
```
