### ISSUE TITLE
rubrik_assign_sla - Invalid object type "oracle_db"

### ISSUE THREAD

**Issue by SpikeyWeasel** [rubrik-devops/ansible-rubrik#120]
**Expected Behavior**

I'd expect to be able to assign an SLA to an oracle-db

**Current Behavior**

The module fails stating the object type is incorrect.

**Failure Information (for bugs)**

* (fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "value of object_type must be one of: vmware, physical_host, ahv, mssql_db, got: oracle_db"})

```
assign_sla.yml
---

- hosts: localhost
  gather_facts: false

  tasks:
    - name: Assign SLA
      rubrikinc.cdm.rubrik_assign_sla
        object_name: "{{ db_name }}"
        object_type: "oracle_db"
        sla_name: "{{ sla_name }}"

```

**Steps to Reproduce**

Invoke playbook above passing db_name as extra-var

**Context**

In terms of versions the API is invoked against the latest Rubrik version from a Python 3.6 virtual environment on RHEL7 OS.

**Failure Logs**

```
(ansible-venv) [ec2-user@ip-10-206-213-66 ansible]$ ansible-playbook --connection=local -i ./local_inventory --extra-vars "db_name=RBK01LB sla_name=\"SPGI Bronze - Local\"" sla_assign.yml

PLAY [localhost] *******************************************************************************************************************************************************************************

TASK [Assign SLA] ******************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "value of object_type must be one of: vmware, mssql_host, volume_group, ahv, got: oracle_db"}

PLAY RECAP *************************************************************************************************************************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

The list of valid object types doesn't appear to be consistent with that supported by the Python SDK that the module uses.
